sprin:
  application:
    name: eurekaserver
  security:
    basic:
      enabled: true
    user:
      name: ms-curso-microservice1
      password: e1sciumrmsc-v-rioeorsc

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
