spring:
  application:
    name: mscloudgateway

  cloud:
    gateway:
      discovery:
        locator:
          enable: true
          lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAL_SERVER}:${KEYCLOAK_PORT}/realms/mscourserealm

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:admin@${EUREKA_SERVER}:8761/eureka


